### ISSUE TITLE
can my dwm rice be showcased here too?

### ISSUE THREAD

**Issue by chadcat7** [zemmsoares/awesome-rices#15]
https://github.com/chadcat7/dwm

its fine if you dont want to

**Comment by Narmis-E** [comment]
Damn I really need to learn dwm and EWW..
Your rice can totally be featured! The repo you provided is only for your decompiled dwm variant right? The repo should try to provide the dotfiles for the programs displayed in the screenshots is what I believe @zemmsoares had in mind. Uploading your dotfiles there or accessible anywhere in some capacity would be great 👍.

**Comment by chadcat7** [comment]
understandable will upload my eww dots as well in the repo as its the only other thing in display

**Comment by zemmsoares** [comment]
@Narmis-E is right, keeping things neat and easy is the way to go! Personally, I can grab some ideas just by glancing at the screenshots, but for the sake of documentation, and for folks who like to dive into the dots, uploading them definitely helps keep things organized. It's fantastic to see people working on these kinds of projects! 💪
