### ISSUE TITLE
Spicing up the README? :fire: 

### ISSUE THREAD

**Issue by Narmis-E** [zemmsoares/awesome-rices#18]
I've had this thought nagging me about ways to give the readme some more pazazz. Perhaps including distro badges for each rice (maybe difficult), adding the screenshots of peoples rices to a gallery dir or expandable <details><summary>{wm}</summary>[user](rice) 
[user](rice)</details> 
sections, a "featured rices" section or "rice of the month". These are all just ideas floating in my head, but maybe a todo section could be helpful for arranging ideas. Thanks

**Comment by zemmsoares** [comment]
Been thinking the same! 
Here are my thoughts on it all. Just my two cents, though. :rabbit2: 

## expandable section
The idea of an expandable section has been on my radar too. But, in practical terms, it could complicate readability and upkeep of the list. Check out the original [awesome list](https://github.com/sindresorhus/awesome) - it's super tidy and user-friendly, even with hundreds of entries.

## Icons on sections / table of contents
Saw your PR on this - great initiative! However, I'm of the same mind as with the expandable list. Including icons in the sections or table of contents might clutter the visual space. Keeping these areas clean and user-friendly is crucial.

## Badges
Now, badges? Big yes! From a usability standpoint, it's  handy for someone who's looking for a specific config - say, for `nvim` or `polybar`. With badges, they could immediately identify what they're looking for without having to dig into every repo.

However, my past experiences with badges have been kind of a mixed bag. Their size often creates a chunky gap between bullet points, and Git's markdown limitations prevent vertical alignment. This wouldn't be an issue with a table, but they tend to occupy a lot of space with many entries. Your repo got me thinking, though, and I tried to create a couple of svgs. And here's a thought - how about a generator for properly aligned badges? 🥇 hehe

I've noticed your badges (awesome-unix-badges) are more compact than the usual, making the alignment issue almost invisible. Kudos on that :muscle: 

Another thing is that badges aren't searchable this way. You can't use `/` or `Find`.

without badges:

- [TorchedSammy](https://github.com/TorchedSammy/dotfiles) - Arch Linux, i3wm
- [vulekhanh](https://github.com/vulekhanh/dotfiles) - Void Linux, Awesome

Badges (1):

- [TorchedSammy](https://github.com/TorchedSammy/dotfiles) - ![](https://custom-icon-badges.demolab.com/badge/Arch--1BADF6.svg?logo=archlinux) ![](https://custom-icon-badges.demolab.com/badge/i3wm--537A9E.svg?logo=i3) 
- [vulekhanh](https://github.com/vulekhanh/dotfiles) - ![](https://custom-icon-badges.demolab.com/badge/Void--478061.svg?logo=void) ![](https://custom-icon-badges.demolab.com/badge/awesome--6791C9.svg?logo=awesome)

Badges (2):

- [zemmsoares]() ![](https://raw.githubusercontent.com/zemmsoares/unix-github-badges/d8731363fe9aab5b0b36992533dd83f11c8bff89/assets/Example3/arch.svg) ![](https://raw.githubusercontent.com/zemmsoares/unix-github-badges/d8731363fe9aab5b0b36992533dd83f11c8bff89/assets/Example3/neovim.svg) ![](https://raw.githubusercontent.com/zemmsoares/unix-github-badges/d8731363fe9aab5b0b36992533dd83f11c8bff89/assets/Example3/code.svg)  
- [Narmis]() ![](assets/Example3/void.svg) ![](https://raw.githubusercontent.com/zemmsoares/unix-github-badges/d8731363fe9aab5b0b36992533dd83f11c8bff89/assets/Example3/neovim.svg) 

## Other than that
What if we had a section purely for wallpaper repos? Also, it might be cool to highlight user-driven projects that stick to the 'rices' theme. I've seen some amazing stuff from our contributors, @Narmis-E badges which ill use right after commenting this, custom music players to modified tiling window managers. We could possibly showcase these in a section at the bottom of the page?

But hey, this is just my opinion Looking forward to hearing your thoughts.
:fire:

**Comment by Narmis-E** [comment]
I'm glad you like the badges, but those second ones look even more snazzy! There are always rice projects popping up from time to time and I think that could look good too, same with the wallpapers. I apologise for forgetting what awesome lists typically adhere to; just words, but adding the badges as links to configs is a great idea.

When you generated the badge for this repo, did you make it from scratch or use some other template? (the colour division length is better than the standard one)

**Comment by zemmsoares** [comment]
No need for apologies! Your thoughts sparked some great ideas.
The badge from the repo ive made it from scratch, kinda :smile: 
i used the vector files from [awesome](https://github.com/sindresorhus/awesome/tree/main/media) badge as a starting point and went from there.

**Comment by Narmis-E** [comment]
Nice, I've been wanting to use Inkscape more so maybe this is a start.

**Comment by zemmsoares** [comment]
Its a great start! 
Just pushed [inline-badges](https://github.com/zemmsoares/inline-badges), its a mess but kinda works :laughing: :fire:

**Comment by Narmis-E** [comment]
Awesome 😎
