### ISSUE TITLE
Broken links for end-4

### ISSUE THREAD

**Issue by clsty** [zemmsoares/awesome-rices#39]
The screenshot links of end-4's config are broken.
(Also for some other ricers actually.)

I've tried to give a Pull Request, though I actually can't find where the pictures locate, e.g. one of them is:

```plain
https://private-user-images.githubusercontent.com/97237370/293474372-abd05702-a248-4f53-ac82-500219aa19f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNTUzODYsIm5iZiI6MTcwODE1NTA4NiwicGF0aCI6Ii85NzIzNzM3MC8yOTM0NzQzNzItYWJkMDU3MDItYTI0OC00ZjUzLWFjODItNTAwMjE5YWExOWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA3MzEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YmJmNDI4NjRmOTIxYzVmMjZjNDhlNTE2NjNjZjJkMmM0ZjQ0YmNmMWNiYjNkOWExOGE4NDE3YzFmZmI3OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fkcxHgK6k5aq-cSl-Iepkz5Lp1qcW2s7_QUQjSFqOfI
```

I mean, you don't want to have such a loooooooooong url in your README, don't you?

---

And, the dots of end-4 now has a wiki (mainly built by me), and here's the showcase:

https://end-4.github.io/dots-hyprland-wiki/en/general/showcase/

You may grab links from there, but it may still change and break another day.

---

Possible suggestions:

- Save the pictures inside this repo, not just refer to a link, so that it will not be broken.
- Use GitHub Pages to build a Gallery website, e.g. by [using a Hugo theme](https://themes.gohugo.io/tags/gallery/). (This will not solve this issue, but it will just looks nicer.)

**Comment by Narmis-E** [comment]
Hi, not exactly sure why the rice image url is that long :/. GitHub pages certainly seems like a good idea, @zemmsoares will need to arrange that if chosen though. I'll look at fixing this in the morning, Thanks!

**Comment by Narmis-E** [comment]
I've grabbed the links from the wiki for now. If it ever changes please let me know. I would love to save everyones rice screenshots locally in this repo, but not sure how easy that will be to maintain/update. Thanks :+1:
