### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by Narmis-E** [zemmsoares/awesome-rices#4]
Hey, 

I made a post on r/unixporn about the repo and so far (one comment lol) people seem to like it. I realise how Reddit is a very different medium in terms of communication compared to GitHub. You might agree, but the environment that sub used to have was quite nice and rich with supportive users. 

I think that a GitHub discussion for this repo might be a nice way to replicate what we used to have on r/unixporn. Perhaps a category for each wm/de might be helpful, or even ones dedicated for specific users if other ricers want to understand their rice better or ask for help (specific to their rice).

Let me know what you think!
Thanks again for making this repo 🙂

**Comment by zemmsoares** [comment]
Hey @Narmis-E !

That's an excellent idea! As long as people get some benefit from it, let's go! I just opened the discussions. 
Let me know if I can add you as a collaborator in order to keep things going! That would be awesome!

Thank you! :muscle:

**Comment by Narmis-E** [comment]
Very nice :ok_hand:! I also just realised that you can only use the default discussion categories -_- but it's better than nothing. It would be my pleasure to lend a helping hand.
